spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:shareit;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
spring.sql.init.schema-locations=classpath:schema.sql
spring.jpa.defer-datasource-initialization=true

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
